'use client';

import { Check, X, Star, Zap } from 'lucide-react';
import { useState } from 'react';

// 🟢 REAL STRIPE LINKS
const MONTHLY_LINK = 'https://buy.stripe.com/9B6cN77KNcnW2hrgXF2ZO00'; // $29
const YEARLY_LINK = 'https://buy.stripe.com/3cI8wRfdf0Fe2hrgXF2ZO01';   // $299

interface PricingModalProps {
  isOpen: boolean;
  onClose: () => void;
  userId: string;
}

export default function PricingModal({ isOpen, onClose, userId }: PricingModalProps) {
  const [billingCycle, setBillingCycle] = useState<'monthly' | 'yearly'>('monthly');

  if (!isOpen) return null;

  const handleUpgrade = () => {
    const link = billingCycle === 'monthly' ? MONTHLY_LINK : YEARLY_LINK;
    window.location.href = `${link}?client_reference_id=${userId}`;
  };

  return (
    <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4">
      <div 
        className="absolute inset-0 bg-black/60 backdrop-blur-sm transition-opacity" 
        onClick={onClose}
      ></div>

      <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden animate-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="bg-slate-900 p-8 text-center relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500"></div>
          <div className="absolute -top-10 -right-10 w-32 h-32 bg-purple-500/20 rounded-full blur-3xl"></div>
          <div className="absolute -bottom-10 -left-10 w-32 h-32 bg-blue-500/20 rounded-full blur-3xl"></div>
          
          <div className="relative z-10">
            <div className="inline-flex items-center justify-center p-3 bg-white/10 rounded-xl mb-4 backdrop-blur-md shadow-inner border border-white/10">
              <Star className="w-8 h-8 text-yellow-400 fill-yellow-400" />
            </div>
            <h2 className="text-3xl font-extrabold text-white mb-2 tracking-tight">Upgrade to Pro</h2>
            <p className="text-slate-400 text-sm">Unlock the full power of MicroFreelanceHub</p>
          </div>

          <button onClick={onClose} className="absolute top-4 right-4 text-slate-500 hover:text-white transition-colors">
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Toggle Switch */}
        <div className="flex justify-center mt-6 mb-2">
            <div className="bg-gray-100 p-1 rounded-full flex relative">
                <button 
                    onClick={() => setBillingCycle('monthly')}
                    className={`px-6 py-2 rounded-full text-sm font-bold transition-all relative z-10 ${billingCycle === 'monthly' ? 'text-slate-900 shadow-sm bg-white' : 'text-gray-500 hover:text-gray-900'}`}
                >
                    Monthly
                </button>
                <button 
                    onClick={() => setBillingCycle('yearly')}
                    className={`px-6 py-2 rounded-full text-sm font-bold transition-all relative z-10 flex items-center gap-2 ${billingCycle === 'yearly' ? 'text-slate-900 shadow-sm bg-white' : 'text-gray-500 hover:text-gray-900'}`}
                >
                    {/* 👇 UPDATED TEXT */}
                    Yearly <span className="text-[10px] bg-green-100 text-green-700 px-1.5 py-0.5 rounded-full uppercase tracking-wide">2 Months Free</span>
                </button>
            </div>
        </div>

        <div className="text-center mb-8">
             <div className="flex items-baseline justify-center gap-1">
                <span className="text-5xl font-extrabold text-slate-900">
                    {billingCycle === 'monthly' ? '$29' : '$299'}
                </span>
                <span className="text-gray-500 font-medium">
                    /{billingCycle === 'monthly' ? 'mo' : 'yr'}
                </span>
             </div>
             <p className="text-xs text-gray-400 mt-2">Cancel anytime. Secure payment via Stripe.</p>
        </div>

        {/* Feature List */}
        <div className="px-8 pb-8">
          <div className="space-y-4 mb-8">
            <FeatureItem text="Unlimited Contracts & Agreements" />
            <FeatureItem text="AI-Powered Contract Generation" />
            <FeatureItem text="Edit & Duplicate Signed Contracts" />
            {/* 👇 UPDATED TEXT */}
            <FeatureItem text="Advanced Income Analytics & Reports" />
            <FeatureItem text="Remove 'Generated By' Branding" />
          </div>

          <button 
            onClick={handleUpgrade}
            className="w-full bg-slate-900 hover:bg-slate-800 text-white font-bold py-4 rounded-xl shadow-lg hover:shadow-xl hover:-translate-y-0.5 transition-all flex items-center justify-center gap-2 group"
          >
            <Zap className="w-5 h-5 text-yellow-400 group-hover:scale-110 transition-transform" />
            {billingCycle === 'monthly' ? 'Start Monthly Subscription' : 'Get 12 Months Access'}
          </button>
        </div>
      </div>
    </div>
  );
}

function FeatureItem({ text }: { text: string }) {
  return (
    <div className="flex items-center gap-3">
      <div className="w-5 h-5 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center shrink-0">
        <Check className="w-3.5 h-3.5 stroke-[3]" />
      </div>
      <span className="text-slate-600 font-medium text-sm">{text}</span>
    </div>
  );
}